### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by tonverra** [jotux/Steward-Platform-Forward-Kinematics-Solver#1]
Hi,

Getting some errors when running the forward kinematics part. I am trying to figure out how the model works, but it is a little much for me.

The error is as following: 
Error in stew>solve_forward (line 840)
            forward_solution=stew_forward(L1,L2,L3,L4,L5,L6,xsi,ysi,xmi,ymi,rollmin,rollmax,pitchmin,pitchmax,yawmin,yawmax,pxmin,pxmax,pymin,pymax,pzmin,pzmax);%this is an
            external function

Error in stew (line 402)
    solve_forward();
 
Error while evaluating UIControl Callback

 I am using R2015a. Could you also provide the paper you are referring to in your comments? I seem to have a version with different equation numbers.

Thank you!

**Comment by jotux** [comment]
Ton,

I wrote this code 9(!!!) years ago when I was an undergraduate and hardly remember how it works. I cannot offer support for the code but wish you luck in using it for your project.
